import tempfile
import unittest
from datetime import date
from pathlib import Path

from reporters.daily_briefing import (
    rank_signals,
    render_daily_briefing,
    write_daily_briefing,
)


def make_signal(
    title="Agent update",
    *,
    company="OpenAI",
    impact_score=3,
    source_tier=1,
    published_at="2026-07-27T08:00:00+08:00",
):
    slug = title.lower().replace(" ", "-")
    return {
        "title": title,
        "canonical_url": f"https://example.com/{slug}",
        "source_name": "Official releases",
        "source_tier": source_tier,
        "platform": "github",
        "company": company,
        "published_at": published_at,
        "summary": "A concise source-backed summary.",
        "why_it_matters": "A concrete product implication.",
        "evidence": ["Official evidence."],
        "topics": ["coding-agents"],
        "impact_score": impact_score,
        "confidence": 0.98,
    }


class DailyBriefingTests(unittest.TestCase):
    def test_ranks_by_impact_then_source_quality(self):
        ranked = rank_signals(
            [
                make_signal("Community", impact_score=3, source_tier=3),
                make_signal("Official", impact_score=3, source_tier=1),
                make_signal("High impact", impact_score=5, source_tier=2),
            ]
        )
        self.assertEqual(
            [signal["title"] for signal in ranked],
            ["High impact", "Official", "Community"],
        )

    def test_briefing_keeps_sources_and_product_boundary(self):
        markdown = render_daily_briefing([make_signal()], date(2026, 7, 27))
        self.assertIn("AI Pulse Daily Brief - 2026-07-27", markdown)
        self.assertIn("generated by AI Intelligence Radar", markdown)
        self.assertIn("https://example.com/agent-update", markdown)
        self.assertIn("Why it matters", markdown)

    def test_empty_briefing_is_honest(self):
        markdown = render_daily_briefing([], date(2026, 7, 27))
        self.assertIn("No signals passed", markdown)
        self.assertIn("signal_count: 0", markdown)

    def test_writes_briefing_under_output_directory(self):
        with tempfile.TemporaryDirectory() as directory:
            path = write_daily_briefing(
                [make_signal()],
                Path(directory),
                date(2026, 7, 27),
            )
            self.assertEqual(path.name, "2026-07-27-ai-pulse.md")
            self.assertTrue(path.exists())


if __name__ == "__main__":
    unittest.main()
