"""Render normalized Radar signals as an AI Pulse daily briefing."""

from __future__ import annotations

import argparse
from datetime import date
from pathlib import Path
from typing import Any, Iterable

from build_knowledge_base import load_signals, parse_published_at


def _impact_score(signal: dict[str, Any]) -> int:
    value = signal.get("impact_score", 0)
    return value if isinstance(value, int) else 0


def rank_signals(
    signals: Iterable[dict[str, Any]],
    limit: int = 10,
) -> list[dict[str, Any]]:
    """Rank already-filtered signals without inventing new facts."""
    if limit < 0:
        raise ValueError("limit must be non-negative.")
    return sorted(
        signals,
        key=lambda signal: (
            _impact_score(signal),
            -int(signal["source_tier"]),
            parse_published_at(signal["published_at"]).timestamp(),
            signal["title"],
        ),
        reverse=True,
    )[:limit]


def render_daily_briefing(
    signals: Iterable[dict[str, Any]],
    report_date: date,
    *,
    limit: int = 10,
) -> str:
    """Render a source-linked daily brief from normalized signals."""
    ranked = rank_signals(signals, limit=limit)
    lines = [
        "---",
        "type: ai-daily-briefing",
        f"date: {report_date.isoformat()}",
        f"signal_count: {len(ranked)}",
        "---",
        "",
        f"# AI Pulse Daily Brief - {report_date.isoformat()}",
        "",
        "> AI Pulse is a daily output generated by AI Intelligence Radar, not a separate product.",
        "",
        "## Top signals",
        "",
    ]

    if not ranked:
        lines.extend(
            [
                "No signals passed the current freshness and evidence gates.",
                "",
            ]
        )
    else:
        for index, signal in enumerate(ranked[:3], start=1):
            lines.extend(
                [
                    f"{index}. **{signal['title']}**",
                    (
                        f"   - Source: {signal['company']} · T{signal['source_tier']} · "
                        f"{signal['source_name']}"
                    ),
                    f"   - Summary: {signal['summary']}",
                    f"   - Why it matters: {signal['why_it_matters']}",
                    f"   - [Verify at source]({signal['canonical_url']})",
                    "",
                ]
            )

    lines.extend(["## More signals", ""])
    if len(ranked) > 3:
        for signal in ranked[3:]:
            lines.append(
                f"- [{signal['title']}]({signal['canonical_url']}) · "
                f"{signal['company']} · {signal['summary']}"
            )
    else:
        lines.append("- No additional signals passed the current gates.")

    lines.extend(
        [
            "",
            "## Evidence boundary",
            "",
            "- This brief only summarizes the normalized signals from the current run.",
            "- Follow the source links before using an item for an important decision.",
            "- Community signals do not become facts without independent T1 evidence.",
            "",
        ]
    )
    return "\n".join(lines)


def write_daily_briefing(
    signals: Iterable[dict[str, Any]],
    output_dir: Path,
    report_date: date,
    *,
    limit: int = 10,
) -> Path:
    briefings_dir = output_dir / "briefings"
    briefings_dir.mkdir(parents=True, exist_ok=True)
    path = briefings_dir / f"{report_date.isoformat()}-ai-pulse.md"
    path.write_text(
        render_daily_briefing(signals, report_date, limit=limit),
        encoding="utf-8",
    )
    return path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Render normalized Radar signals as an AI Pulse daily briefing."
    )
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--date", default=date.today().isoformat(), help="YYYY-MM-DD")
    parser.add_argument("--limit", type=int, default=10)
    args = parser.parse_args()
    signals = load_signals(args.input)
    path = write_daily_briefing(
        signals,
        args.output,
        date.fromisoformat(args.date),
        limit=args.limit,
    )
    print(f"signals={min(len(signals), args.limit)} saved={path}")


if __name__ == "__main__":
    main()
